spring:
 #激活哪一个环境的配置文件
  profiles:
    #active: dev
    active: pro
  jackson:
    # 属性为NULL 不序列化
    default-property-inclusion: non_null
qiniu:
  accessKey: wJeRHTcGicloBEUjyNYVYa0W9ZQZvI7j9dTd5FFl
  secretKey: ZCu_Pn0IJ3z2rVB7Z-fn1YaJMUGqG1ab-ubD6pX9
  #baseUrl: http://img.emucoo.net
  baseUrl: pp8a46bxe.bkt.clouddn.com
  bucket: sangss
  expires: 3600

token:
  expire: 12

ali_return_url: 同步回调地址
ali_notify_url: http://81.70.149.138:8081/api/task/getNotifyUrlInfo

#销售产品码，商家和支付宝签约的产品码，为固定值QUICK_MSECURITY_PAY.业务参数,拼接时放在biz_content中
ali_product_code: QUICK_MSECURITY_PAY

#该笔订单允许的最晚付款时间，逾期将关闭交易。
ali_timeout_express: 30m
ali_url: https://openapi.alipay.com/gateway.do
ali_appid: 2021001196685328
ali_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC8SNhvp+TGiUTISVq57qgliflJEnD06ObTliOYen5spFmiv8lzKfbL63c0S9hR1I3TG1J/GeSsDQ4fHoa1oQ/N4CIgINu//J5xqqbgA2To5cBeMwfV57dG+DBUMDXAX/uCqzhKUDIQEy0/lZsDIEg3APl/iOuAvIvZ0Dwhg41QycQArCuMeNdCt4Z44vYF/6MOPuVwgxVuMCJmrv9Drhay6c04hJKuRaCOReuLuRcLU+fwc0cjXD1gx9cCxqIJ8zHAvh78PCnqPVERJUFTIwe14RaD8pmELRVNhQxw2FHDzGf+s6LJ8Z9c3PjMrHAL2wMbGyZreD7YsEy8RKSYAfsPAgMBAAECggEBAJemEHU2BASIcRbkRie1ekbp7xeUu9f2clv+9GKOXp9AbFWyJR4VsYqi91rur6eRDD35JqPqhgyxYytbWeKWe/U0zieUb4odfLxOV6Pb9/3BdwQoE+qMfEi0A7D7N3/fjuK651aravcZivtIkxacfK2Yolu/OvdwZS+lEZlorHxg8rPiU3sUPB7PuGSQ4iTt2ulZ0TmLGS2fHPXVkogfbSomn3QXuHAMfEKmBYljTUU3zjqSx6CmNPPOTXdsN9vslQYNtjshbkIMp2bjwi2pAi8jZAJ5oJAtMt0swFMjF5WLGy7rsU+q2cozJFsG+XNgpXIOJxKymS7rbcc4Spl+RLkCgYEA8W007KLTLElOAEXKzjx6WOzvKxG3aN0jWHsgqIClMVsOJiSsk6yNc1TlcJufMe6SWQYKRyBMm9c+EiA6XFyL9TlW1Qvmhgy+Av4IjAUjp8S3e4e2RYlQ+mxUxGNiofNoh8qzFWK7NtQEDGJ3jlj3gan8iM0YHUkZevCiND3WSa0CgYEAx6ZtuoJsjg8lLJKe6kSA5DqJcYTNaqJS4YjM7y9QH9lhJaQSrUhlmLdA8g2qrLrrYF/iLEKQ4vn07OwBtw/FWSjQIvnMWmgo/qBdFcB6R98YEA/HCyt9kj9cOUBXqt+wJ9/QYeSv+Qf3qgE/xGsf80i92IQf8tbzr6d0R1y7ZysCgYEAuj4xzr8JQyfFqYYtno2fIIyfME15fMbjZnWNyw964ClLL/eovj8l26vJV+Zll8JgWZbERPxQvQP92UPNYcTvHxy9tJp6mjyoNGy+MS4hxGGH3h7iaKA2vQjnF51H0IGSyPaA0mWY4QILoXYwnrpZLUjyDKKTELx8kI+jwcNWVP0CgYA7Ys/k2IK9xteB6KMIgBPuz1Kux5fqjholJ/H9e49Tye9RqPo9PPmrcWcKGPKZqof1BNBb5fj+6ublylXARBqpqLAwlykoAy+efcjyfWxiEIQx0t+b/PW/GMWv6emp1Bur4LE1TTbi1nHeybxUCqFYVlzSGIsAStv1ddPqnjTIPQKBgBJUMJyRFfFPIbJGilm85Brmqx+nIrYVf+gCVO28/aaw0FqsamgWZjRcxVzmxQAm+XDUkGZYMqAnp8KhxU1/r4G7jCVDA6C+dMZo1CGbFYvpn7smxGv53lBHJQYPEoYfnhF2NO0MupOUl2oCurS/gyOGEXhm4zr6felvfGnfXJVv
ali_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg56rCOawu3nB11n8pca49zP2ryrdlp3tI/yqn6KyUwKqZs8lMQ30qy/NnWZr2/2UrdhGBtnfPGrwCyb6DFVasQK8k/c3smiv04xOvlbFAXJr4FOaTdlgxwJnhIgFfHZrNrVNzm6/G9SpvLg5bhLArFFshq6e8fS/q8kKWI290me2VRZKjGMOzUZ1uLBcuqcVmJcuUQQBGRP08YBUu3XmWvfIXgN9NGXH6NYFdhgSK2/rKw0kY9V8P1+wl/Q43NZrL8rIRfjQUwJimbZ8D4TvQj0r1btAg1iRcAzsP1GRAlBVEzS2IrfQ77lKNw0nU8ngkINlEwI7Q1TtOD19H/73WQIDAQAB
ali_sign_type: RSA2


